### ISSUE TITLE
Confusion about LICENSE

### ISSUE THREAD

**Issue by Zxilly** [goretk/gore#75]
I am using gore to create my own project [gsv](https://github.com/Zxilly/go-size-view), but my project is released under the Mozilla Public License 2.0, and I'm not sure if this is compatible with the AGPL that gore uses, so I'd like to get an explicit permit from the author for this use.
Thank you sincerely for your work on gore.

**Comment by TcM1911** [comment]
IANAL, and this is just my understanding. AGPLv3 is essentially GPLv3 with the extra restriction that if you serve it over a network, you have to make the source available. The reason why **gore** was licensed under AGPL was to not allow someone to use it in for example a SaaS product without sharing the code back to the community.

According to the license, if you use an AGPL library to create a combined work, the combined work must be licensed under AGPL. 

With regards to MPL, Mozilla's [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) for MPL has this Q/A:

> **Q14: May I combine MPL-licensed code and (L)GPL-licensed code in the same executable program?**
> Yes, by creating a "Larger Work" under the terms of Section 3.3. In particular, three requirements must be met:
> 
> The software must not be “Incompatible With Secondary Licenses.” Software can become “Incompatible With Secondary Licenses” in one of two ways: the original author marks it as such by adding the file header in Exhibit B, or the original author published the software under MPL 1.1 and did not dual- or tri-license the code with the (L)GPL.
> 
> The Larger Work must be "a combination of Covered Software with a work governed by one or more Secondary Licenses." So you can't just say "I really prefer (L)GPL" - you must have a need to combine with another, existing GPL work. (This is different from a traditional dual-license, which does not require you to combine, and instead allows you to simply say "I've decided to be GPL-only.")
> 
> You must "additionally distribute" under (L)GPL. In other words, you must make the MPL-licensed source code available to your recipients under both MPL and (L)GPL. Someone downstream from your recipients can then take under (L)GPL-only or MPL-only. This is different from a traditional dual-license, which never requires publication under both licenses, and so always gives you the option of releasing incompatibly-licensed code.

Which looks like you can use AGPL code in **gsv** as long as you dual license the source files under MPLv2.0 and AGPLv3. The produced binaries have to be distributed under AGPL. Any derivative work from **gsv** will also have to be licensed using AGPL, but anyone can take the **gsv** source files that do not use **gore** and use them under the MPL license since they will be dual licensed. To make this easier, I would either:
1. Put all interaction with **gore** into one file that can be easily removed.
2. Move most of the code into a new library that can be licensed under MPL. Have a "small" repo for **gsv** that imports the MPL library and **gore** which is licensed under AGPL.

If you are not planning for **gsv** to be used in other combined works, the easiest is just to distributed it all under AGPL.

How to go from here, depends what your end goal is.

Does this answer your question?

**Comment by Zxilly** [comment]
Thanks for your reply, I think it would be a good idea to relicense the code under the AGPL.
